# Description
title: Paris-Web 2017

# configuration
baseurl: /jekyll-paris-web
theme: minima

collections:
  themes:
    output: true

default:
  - scope:
    path:
    type: "themes"
  value:
    layout: post
